// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales =
  | "en"
  | "es"
  | "fr"
  | "ja"
  | "ko"
  | "pt"
  | "zh-CN"
  | "zh-HK"
  | "zh-TW";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  settings: {
    /**
     * S​h​o​w​ ​a​f​t​e​r
     */
    delayLabel: string;
    /**
     * D​u​r​a​t​i​o​n
     */
    durationLabel: string;
    /**
     * L​a​n​g​u​a​g​e
     */
    languageLabel: string;
    /**
     * P​r​e​v​i​e​w
     */
    preview: string;
    /**
     * G​i​t​H​u​b
     */
    github: string;
    /**
     * M​a​d​e​ ​b​y​ ​E​l​l​i​o​t​ ​a​n​d​ ​h​i​s​ ​d​a​u​g​h​t​e​r​ ​"​毛​球​"​ ​(​t​h​e​ ​n​a​m​e​ ​m​e​a​n​s​ ​"​f​l​u​f​f​y​ ​f​u​r​b​a​l​l​"​;​ ​s​h​e​ ​i​s​ ​a​ ​4​-​y​e​a​r​-​o​l​d​ ​N​o​r​w​e​g​i​a​n​ ​F​o​r​e​s​t​ ​c​a​t​)​.
     */
    credit: string;
  };
  durations: {
    /**
     * 1​5​s
     */
    seconds15: string;
    /**
     * 3​0​s
     */
    seconds30: string;
    /**
     * 1​m​i​n
     */
    minutes1: string;
    /**
     * 1​.​5​m​i​n
     */
    minutes1_5: string;
    /**
     * 2​m​i​n
     */
    minutes2: string;
    /**
     * 3​m​i​n
     */
    minutes3: string;
    /**
     * 5​m​i​n
     */
    minutes5: string;
    /**
     * 1​0​m​i​n
     */
    minutes10: string;
    /**
     * 1​5​m​i​n
     */
    minutes15: string;
    /**
     * 3​0​m​i​n
     */
    minutes30: string;
    /**
     * 1​h
     */
    hours1: string;
    /**
     * 1​.​5​h
     */
    hours1_5: string;
    /**
     * 2​h
     */
    hours2: string;
    /**
     * 3​h
     */
    hours3: string;
  };
  languages: {
    /**
     * E​n​g​l​i​s​h
     */
    en: string;
    /**
     * 简​体​中​文
     */
    zhCN: string;
    /**
     * 繁​體​中​文​（​香​港​）
     */
    zhHK: string;
    /**
     * 繁​體​中​文​（​台​灣​）
     */
    zhTW: string;
    /**
     * 日​本​語
     */
    ja: string;
    /**
     * 한​국​어
     */
    ko: string;
    /**
     * E​s​p​a​ñ​o​l
     */
    es: string;
    /**
     * F​r​a​n​ç​a​i​s
     */
    fr: string;
    /**
     * P​o​r​t​u​g​u​ê​s
     */
    pt: string;
  };
  screensaver: {
    /**
     * P​r​e​v​i​e​w
     */
    previewTitle: string;
    /**
     * T​a​k​e​ ​a​ ​b​r​e​a​k
     */
    manualTitle: string;
    /**
     * T​i​m​e​ ​t​o​ ​r​e​s​t
     */
    scheduledTitle: string;
    /**
     * L​O​O​K​ ​A​W​A​Y
     */
    headline: string;
    /**
     * R​e​s​t​ ​y​o​u​r​ ​e​y​e​s​ ​u​n​t​i​l​ ​t​h​e​ ​c​o​u​n​t​d​o​w​n​ ​f​i​n​i​s​h​e​s​.
     */
    body: string;
    /**
     * C​l​o​s​e​ ​s​c​r​e​e​n​s​a​v​e​r
     */
    close: string;
  };
  tray: {
    /**
     * O​p​e​n​ ​A​p​p
     */
    openApp: string;
    /**
     * S​h​o​w​ ​n​o​w
     */
    show: string;
    /**
     * C​l​o​s​e​ ​n​o​w
     */
    hide: string;
    /**
     * Q​u​i​t
     */
    quit: string;
  };
};

export type TranslationFunctions = {
  settings: {
    /**
     * Show after
     */
    delayLabel: () => LocalizedString;
    /**
     * Duration
     */
    durationLabel: () => LocalizedString;
    /**
     * Language
     */
    languageLabel: () => LocalizedString;
    /**
     * Preview
     */
    preview: () => LocalizedString;
    /**
     * GitHub
     */
    github: () => LocalizedString;
    /**
     * Made by Elliot and his daughter "毛球" (the name means "fluffy furball"; she is a 4-year-old Norwegian Forest cat).
     */
    credit: () => LocalizedString;
  };
  durations: {
    /**
     * 15s
     */
    seconds15: () => LocalizedString;
    /**
     * 30s
     */
    seconds30: () => LocalizedString;
    /**
     * 1min
     */
    minutes1: () => LocalizedString;
    /**
     * 1.5min
     */
    minutes1_5: () => LocalizedString;
    /**
     * 2min
     */
    minutes2: () => LocalizedString;
    /**
     * 3min
     */
    minutes3: () => LocalizedString;
    /**
     * 5min
     */
    minutes5: () => LocalizedString;
    /**
     * 10min
     */
    minutes10: () => LocalizedString;
    /**
     * 15min
     */
    minutes15: () => LocalizedString;
    /**
     * 30min
     */
    minutes30: () => LocalizedString;
    /**
     * 1h
     */
    hours1: () => LocalizedString;
    /**
     * 1.5h
     */
    hours1_5: () => LocalizedString;
    /**
     * 2h
     */
    hours2: () => LocalizedString;
    /**
     * 3h
     */
    hours3: () => LocalizedString;
  };
  languages: {
    /**
     * English
     */
    en: () => LocalizedString;
    /**
     * 简体中文
     */
    zhCN: () => LocalizedString;
    /**
     * 繁體中文（香港）
     */
    zhHK: () => LocalizedString;
    /**
     * 繁體中文（台灣）
     */
    zhTW: () => LocalizedString;
    /**
     * 日本語
     */
    ja: () => LocalizedString;
    /**
     * 한국어
     */
    ko: () => LocalizedString;
    /**
     * Español
     */
    es: () => LocalizedString;
    /**
     * Français
     */
    fr: () => LocalizedString;
    /**
     * Português
     */
    pt: () => LocalizedString;
  };
  screensaver: {
    /**
     * Preview
     */
    previewTitle: () => LocalizedString;
    /**
     * Take a break
     */
    manualTitle: () => LocalizedString;
    /**
     * Time to rest
     */
    scheduledTitle: () => LocalizedString;
    /**
     * LOOK AWAY
     */
    headline: () => LocalizedString;
    /**
     * Rest your eyes until the countdown finishes.
     */
    body: () => LocalizedString;
    /**
     * Close screensaver
     */
    close: () => LocalizedString;
  };
  tray: {
    /**
     * Open App
     */
    openApp: () => LocalizedString;
    /**
     * Show now
     */
    show: () => LocalizedString;
    /**
     * Close now
     */
    hide: () => LocalizedString;
    /**
     * Quit
     */
    quit: () => LocalizedString;
  };
};

export type Formatters = {};
